# Generated by Django 2.0 on 2019-10-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='deparment',
            new_name='department',
        ),
    ]
