# Generated by Django 2.0 on 2019-10-10 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_names', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('', 'Choose your gender'), ('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField(default='1970-01-01')),
                ('state_of_origin', models.CharField(max_length=100)),
                ('lga_of_origin', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=15)),
                ('faculty', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('jamb_reg_no', models.CharField(max_length=15)),
                ('mode_of_entry', models.CharField(max_length=15)),
                ('course_of_study', models.CharField(max_length=50)),
                ('passport', models.ImageField(upload_to='users/applicants/passports')),
                ('admitted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
