# Generated by Django 2.0 on 2019-10-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='course_of_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Course'),
        ),
    ]
