# Generated by Django 2.0 on 2019-10-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='te@g.com', max_length=254),
            preserve_default=False,
        ),
    ]
